addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
before_install:
- export CC="gcc -O3 -std=c99" CXX="g++ -O3 -std=c99"
install: true
script:
- git clone https://github.com/classabbyamp/espresso-logic
- ls -ahl
- cd espresso-logic/espresso-src
- make
- cd ../..
- python blgen.py
- ls -ahl
- head -n 30 tst
- ./espresso-logic/bin/espresso tst > res
- ls -ahl
- head -n 30 res
- tar czf  res.tar.gz res
- ls -ahl

#- find -type f -size +500k -exec ls -lh '{}' \;
#- du -chs docs/en/*


deploy:
  skip_cleanup: true
  provider: releases
#  user: "beshkoon"
#  password: ""
  api_key: "${test2}"
  file: "res.7z"
  on:
    tags: false
